version: "3"
services:
  hexagony:
    container_name: "hexagony"
    image: node:10
    volumes:
      - ./:/opt/app
    working_dir: /opt/app
    ports:
      - 8801-8810:8801-8810
      - 9229:9229
    links:
      - mongodb
    depends_on:
      - mongodb
    tty: true
  mongodb:
    image: mongo:4
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /home/alberto/code/dkr/mongodb:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  mongoclient:
    image: mongoclient/mongoclient
    container_name: "mongoclient"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    ports:
      - 27027:3000
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - /home/alberto/code/dkr/mongoclient:/data/db
